#!/bin/sh

# Copyright (c) 2003 Jack Twilley <jmt@twilley.org>

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

datadir=/web/home/jmt/morse
#lameopts="--quiet -f -m s -a --preset 8"
lameopts="--quiet -f -m s -a --resample 8"
char=20

# build it
for num in 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43; do 
  /home/jmt/bin/newkoch.pl $num > $datadir/tomorrow/$num.txt
  for word in 20 13 5; do
    /home/jmt/bin/tomorse -c $char -s $word < $datadir/tomorrow/$num.txt > $datadir/tomorrow/$num-$word.wav && (/usr/local/bin/lame $lameopts $datadir/tomorrow/$num-$word.wav $datadir/tomorrow/$num-$word.mp3 2>/dev/null) && rm $datadir/tomorrow/$num-$word.wav
  done
done 
